export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_EXPENSES = 'GET_EXPENSES';
export const EXPENSE_LOADING = 'EXPENSE_LOADING';
export const EDIT_EXPENSES = 'EDIT_EXPENSES';
export const DELETE_EXPENSES = 'DELETE_EXPENSES';
export const CLEAR_CURRENT_EXPENSES = 'CLEAR_CURRENT_EXPENSES';

